version: "3.9"

networks:
  deploy-dev:
    driver: bridge

services:
  app: 
    container_name: user-permissions
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "28080:80"
    networks:
      - deploy-dev
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pem1812
      POSTGRES_DB: user-permissions
    ports:
      - "5432:5432"
    networks:
      - deploy-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: