// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using user_permissions;

#nullable disable

namespace user_permissions.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240213113436_1.0.0")]
    partial class _100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IO.Swagger.Models.UserPermissions", b =>
                {
                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.Property<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("UserRole");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            UserRole = "MANAGER",
                            Permissions = new List<string> { "PERM_ABSENCE_MANAGER_READ", "PERM_HEALTHCHECK_MANAGER_READ", "PERM_MYDEPARTMENTS_MANAGER_READ" }
                        },
                        new
                        {
                            UserRole = "HRPARTNER",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_ADD", "PERM_MYDEPARTMENTS_READ" }
                        },
                        new
                        {
                            UserRole = "HRDEV",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_MYDEPARTMENTS_READ" }
                        },
                        new
                        {
                            UserRole = "SUPERUSER",
                            Permissions = new List<string> { "PERM_USER_ROLE_ADD", "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_ADD", "PERM_MYDEPARTMENTS_READ" }
                        });
                });

            modelBuilder.Entity("IO.Swagger.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            UserLogin = "Anna",
                            _UserRole = "MANAGER"
                        },
                        new
                        {
                            Id = "2",
                            UserLogin = "Denis",
                            _UserRole = "HRPARTNER"
                        },
                        new
                        {
                            Id = "3",
                            UserLogin = "Oleg",
                            _UserRole = "HRDEV"
                        },
                        new
                        {
                            Id = "4",
                            UserLogin = "Roman",
                            _UserRole = "SUPERUSER"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
