// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using user_permissions;

#nullable disable

namespace user_permissions.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240214162324_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IO.Swagger.Models.UserPermissions", b =>
                {
                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.Property<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("UserRole");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            UserRole = "employee",
                            Permissions = new List<string>()
                        },
                        new
                        {
                            UserRole = "manager",
                            Permissions = new List<string> { "PERM_ABSENCE_MANAGER_READ", "PERM_HEALTHCHECK_MANAGER_READ", "PERM_MYDEPARTMENTS_MANAGER_READ", "PERM_TASK_SUBJECT_MANAGER_ADD", "PERM_TASK_PERF_MANAGER_ADD", "PERM_TASK_WATCHER_ADD", "PERM_GOALS_MANAGER_READ", "PERM_ONBOARDING_MANAGER_READ", "PERM_EQUIPMENT_MANAGER_READ", "PERM_TRANSITIONS_MANAGER_READ" }
                        },
                        new
                        {
                            UserRole = "hrpartner",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_FULL", "PERM_MYDEPARTMENTS_READ", "PERM_GOALS_READ", "PERM_ONBOARDING_READ", "PERM_EQUIPMENT_READ", "PERM_TRANSITIONS_READ" }
                        },
                        new
                        {
                            UserRole = "hrdev",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_MYDEPARTMENTS_READ", "PERM_GOALS_READ" }
                        },
                        new
                        {
                            UserRole = "superuser",
                            Permissions = new List<string> { "PERM_USER_ROLE_ADD", "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_FULL", "PERM_MYDEPARTMENTS_READ", "PERM_TASK_FULL", "PERM_GOALS_READ", "PERM_ONBOARDING_READ", "PERM_EQUIPMENT_READ", "PERM_TRANSITIONS_READ" }
                        });
                });

            modelBuilder.Entity("IO.Swagger.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = "3000",
                            UserLogin = "djaz",
                            _UserRole = "superuser"
                        },
                        new
                        {
                            Id = "3001",
                            UserLogin = "kazurus",
                            _UserRole = "manager"
                        },
                        new
                        {
                            Id = "3002",
                            UserLogin = "nomad",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "1",
                            UserLogin = "etna",
                            _UserRole = "hrpartner"
                        },
                        new
                        {
                            Id = "2",
                            UserLogin = "manager",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "3",
                            UserLogin = "kortex",
                            _UserRole = "manager"
                        },
                        new
                        {
                            Id = "4",
                            UserLogin = "b3n",
                            _UserRole = "manager"
                        },
                        new
                        {
                            Id = "5",
                            UserLogin = "sempai",
                            _UserRole = "hrdev"
                        },
                        new
                        {
                            Id = "6",
                            UserLogin = "kojima",
                            _UserRole = "hrpartner"
                        },
                        new
                        {
                            Id = "7",
                            UserLogin = "asimar",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "8",
                            UserLogin = "invasion",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "9",
                            UserLogin = "holix",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "10",
                            UserLogin = "alius29",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "11",
                            UserLogin = "nymeria",
                            _UserRole = "hrpartner"
                        },
                        new
                        {
                            Id = "12",
                            UserLogin = "wezen",
                            _UserRole = "manager"
                        },
                        new
                        {
                            Id = "13",
                            UserLogin = "oqaris",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "14",
                            UserLogin = "kurs",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "15",
                            UserLogin = "gigachad",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "16",
                            UserLogin = "frogmonarch",
                            _UserRole = "hrdev"
                        },
                        new
                        {
                            Id = "17",
                            UserLogin = "fox",
                            _UserRole = "hrpartner"
                        },
                        new
                        {
                            Id = "18",
                            UserLogin = "distortion",
                            _UserRole = "hrpartner"
                        },
                        new
                        {
                            Id = "19",
                            UserLogin = "degree",
                            _UserRole = "employee"
                        },
                        new
                        {
                            Id = "20",
                            UserLogin = "resolute",
                            _UserRole = "manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
