// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using user_permissions;

#nullable disable

namespace user_permissions.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IO.Swagger.Models.UserPermissions", b =>
                {
                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.Property<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("UserRole");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            UserRole = "EMPLOYEE",
                            Permissions = new List<string>()
                        },
                        new
                        {
                            UserRole = "MANAGER",
                            Permissions = new List<string> { "PERM_ABSENCE_MANAGER_READ", "PERM_HEALTHCHECK_MANAGER_READ", "PERM_MYDEPARTMENTS_MANAGER_READ", "PERM_TASK_SUBJECT_MANAGER_ADD", "PERM_TASK_PERF_MANAGER_ADD", "PERM_TASK_WATCHER_ADD", "PERM_GOALS_MANAGER_READ", "PERM_ONBOARDING_MANAGER_READ", "PERM_EQUIPMENT_MANAGER_READ", "PERM_TRANSITIONS_MANAGER_READ" }
                        },
                        new
                        {
                            UserRole = "HRPARTNER",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_FULL", "PERM_MYDEPARTMENTS_READ", "PERM_GOALS_READ", "PERM_ONBOARDING_READ", "PERM_EQUIPMENT_READ", "PERM_TRANSITIONS_READ" }
                        },
                        new
                        {
                            UserRole = "HRDEV",
                            Permissions = new List<string> { "PERM_ABSENCE_READ", "PERM_MYDEPARTMENTS_READ", "PERM_GOALS_READ" }
                        },
                        new
                        {
                            UserRole = "SUPERUSER",
                            Permissions = new List<string> { "PERM_USER_ROLE_ADD", "PERM_ABSENCE_READ", "PERM_HEALTHCHECK_FULL", "PERM_MYDEPARTMENTS_READ", "PERM_TASK_FULL", "PERM_GOALS_READ", "PERM_ONBOARDING_READ", "PERM_EQUIPMENT_READ", "PERM_TRANSITIONS_READ" }
                        });
                });

            modelBuilder.Entity("IO.Swagger.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            UserLogin = "employee",
                            _UserRole = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "2",
                            UserLogin = "manager",
                            _UserRole = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            UserLogin = "hrpartner",
                            _UserRole = "HRPARTNER"
                        },
                        new
                        {
                            Id = "4",
                            UserLogin = "hrdev",
                            _UserRole = "HRDEV"
                        },
                        new
                        {
                            Id = "5",
                            UserLogin = "superuser",
                            _UserRole = "SUPERUSER"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
