version: "3.9"

networks:
  deploy-dev:
    driver: bridge

services:
  postgres_db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pem1812
      POSTGRES_DB: user-permissions
    ports:
      - "5432:5432"
    networks:
      - deploy-dev
    volumes:
      - postgres-data:/var/lib/pgsql/data
      
  app: 
    container_name: user-permissions
    build: .
    ports:
      - "21813:443"
      - "21812:80"
    networks:
      - deploy-dev
    depends_on:
      - postgres_db

      
volumes:
  postgres-data: